---
title: "Tidytuesday 2021-03-02"
output:
  pdf_document:
    latex_engine: xelatex
  html_document: default
---

## Get the Data

```{r, echo=TRUE, message=FALSE, warning=FALSE}
library(tidytuesdayR)
library(tidyverse)

tuesdata <- tidytuesdayR::tt_load('2021-03-02')

youtube <- tuesdata$youtube

```


## Data Wrangling and Visualization

```{r, echo=TRUE, message=FALSE, warning=FALSE}
youtube1 <- youtube %>%
  group_by(year) %>%
  mutate(Contains_humor = sum(funny)) %>%
  mutate(Show_Product_Quickly = sum(show_product_quickly)) %>%
  mutate(Patriotic = sum(patriotic)) %>%
  mutate(Contains_celebrity = sum(celebrity)) %>%
  mutate(Contains_danger = sum(danger)) %>%
  mutate(Contains_animals = sum(animals)) %>%
  mutate(Uses_sexuality = sum(use_sex))

youtube1 <- youtube1 %>%
  select(year, Contains_humor, Show_Product_Quickly, Patriotic, Contains_celebrity, Contains_danger, Contains_animals, Uses_sexuality) %>%
  pivot_longer(-c(year), names_to = "characteristic", values_to = "count"
  )
  
youtube1 %>% 
  ggplot(aes(x = year, y = count)) + geom_bar(stat = "identity") +
  labs(title = "Characteristics of Ads used in Different Years since 2000",
       x = "Year",
       y = "Number of characteristics used") +
  facet_wrap(~characteristic)
```
